=== AlexCheong/mobilis/Emulation/GWTEmulationServer/src/script-utils/XMLEmulationScript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" xmlns:tns="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" elementFormDefault="qualified">
	
	<complexType name="parameterType">
		<sequence>
			<choice maxOccurs="unbounded">
				<element name="int" type="int"/>
				<element name="string" type="string"/>
				<element name="boolean" type="boolean"/>
				<element name="double" type="double"/>
			</choice>
		</sequence>
	</complexType>
	
	<element name="instance" substitutionGroup="tns:setupCommand" type="tns:instanceType"/>
	
	<complexType name="instanceType">
		<complexContent>
			<extension base="tns:setupCommandType">
				<attribute name="varName" type="string"/>
				<attribute name="appNS" type="string"/>
				<attribute name="instanceId" type="int"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="for" substitutionGroup="tns:structure" type="tns:forType"/>
	
	<complexType name="forType">
		<complexContent>
			<extension base="tns:structureType">
				<attribute name="times" type="int"/>
			</extension>		
		</complexContent>
	</complexType>
	
	<element name="structure" abstract="true" substitutionGroup="tns:command" type="tns:structureType"/>
	
	<complexType name="structureType">
		<complexContent>
			<extension base="tns:commandType">
				<sequence>
					<choice>
						<element ref="tns:for"/>
						<!-- other loop types? -->
						<!-- a block issues code to be sent to the client in one block-->
						<element name="block"/>
					</choice>
					<element ref="tns:command" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="appCommand" substitutionGroup="tns:atomicCommand" type="tns:appCommandType"/>
	
	<complexType name="appCommandType">
		<complexContent>
			<extension base="tns:atomicCommandType">
				<sequence>
		            <element name="instance" type="string"/>
		            <element name="methodName" type="string"/>
					<element name="parameter" type="tns:parameterType" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="setupMethods" abstract="true" substitutionGroup="tns:setupCommand" type="tns:setupMethodsType"/>
		
	<complexType name="setupMethodsType">
		<complexContent>
			<extension base="tns:setupCommandType">
				<attribute name="instance" type="string"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="start" substitutionGroup="tns:setupMethods" type="tns:startType"/>
	
	<complexType name="startType">
		<complexContent>
			<extension base="tns:setupMethodsType"/>
		</complexContent>
	</complexType>
	
	<element name="stop" substitutionGroup="tns:setupMethods" type="tns:stopType"/>
	
	<complexType name="stopType">
		<complexContent>
			<extension base="tns:setupMethodsType"/>
		</complexContent>
	</complexType>
	
	<element name="setupCommand" abstract="true" substitutionGroup="tns:atomicCommand" type="tns:setupCommandType"/>
	
	<complexType name="setupCommandType">
		<complexContent>
			<extension base="tns:atomicCommandType"/>
		</complexContent>
	</complexType>
	
	<element name="wait" substitutionGroup="tns:controlCommand" type="tns:waitType"/>
	
	<complexType name="waitType">
		<complexContent>
			<extension base="tns:controlCommandType">
				<attribute name="time" type="int"/>
			</extension>
		</complexContent>
	</complexType>
	
	<element name="controlCommand" substitutionGroup="tns:atomicCommand" type="tns:controlCommandType" abstract="true"/>
	
	<complexType name="controlCommandType">
		<complexContent>
			<extension base="tns:atomicCommandType"/>
		</complexContent>
	</complexType>
	
	<element name="atomicCommand" abstract="true" substitutionGroup="tns:command" type="tns:atomicCommandType"/>
	
	<complexType name="atomicCommandType">
		<complexContent>
			<extension base="tns:commandType"/>	
		</complexContent>
	</complexType>
	
	<element name="command" abstract="true" type="tns:commandType"/>
	
	<complexType name="commandType"/>

    <element name="script">
    	<complexType>
    		<sequence>
    			<element ref="tns:command" minOccurs="0" maxOccurs="unbounded"/>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== AlexCheong/mobilis/Emulation/GWTEmulationServer/src/script-utils/testScript.xml
<?xml version="1.0" encoding="UTF-8"?>
<script xmlns="http://mobilis.inf.tu-dresden.de/XMLEmulationScript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mobilis.inf.tu-dresden.de/XMLEmulationScript XMLEmulationScript.xsd">
   <setupCommand>
       <instanceVarDeclaration varName="PALatency1" appNS="de.tudresden.inf.rn.mobsda.performance.latency" instanceId="1"/>
   </setupCommand>
   <setupCommand>
       <instance>PALatency1</instance>
       <start/>
   </setupCommand>
   <testCommand>
       <instance>PALatency1</instance>
       <methodName>initMeasurements</methodName>
       <parameter>
           <string>measurer1@mobsda.inf.tu-dresden.de</string>
           <string>measurer1</string>
           <string>mobsda:powerassistant:fuellevel</string>
       </parameter>
   </testCommand>
</script>
